name: Build and Deploy lascorbe.com

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
      
    - name: Generate blog
      run: swift run LascorbeCom
      
    - name: Publish deploy
      uses: crazy-max/ghaction-github-pages@v1.4.0
      with:
        repo: lascorbe/lascorbe.github.io
        target_branch: master
        keep_history: true
        allow_empty_commit: false
        build_dir: Output
        committer_name: lascorbe 
        commit_message: Publish deploy from LascorbeCom
      env:
        GITHUB_PAT: ${{ secrets.DEPLOYMENT_TOKEN }}
        
    - name: Add & Commit changes
      uses: EndBug/add-and-commit@v4.0.1
      with:
        author_name: lascorbe
        message: Commit Output
